### ISSUE TITLE
filter by another field

### ISSUE THREAD

**Issue by Razz21** [vuestorefront/storefront-query-builder#27]
Hi,
is it possible with this query builder to create filters that can compare with another field value?
like:
```
query.applyFilter({ key: 'special_price', value: { 'lt': "price" } })
query.applyFilter({ key: 'special_price', value: { lt: 'price.value' } })
query.applyFilter({ key: 'special_price', value: { lt: 'doc['price'].value' } })
```
None of above do work

**Comment by saraElsanan** [comment]
@Razz21  Did ay of them worked , cause we are trying to do the same and no luck , so how did you fix it ?
